service: my-service
provider:
  name: aws
  runtime: nodejs18.x
  environment:
    MONGO_URI: mongodb+srv://admin:admin@g2mdb.spmzf.mongodb.net/g2mdb
    JWT_SECRET: your-secret-key
    CLOUDINARY_CLOUD_NAME: dnn3qcxv5
    CLOUDINARY_API_KEY: 831711536942119
    CLOUDINARY_API_SECRET: PtMttll1lT-yw_rEi0_ZvZ3lMRI

functions:
  app:
    handler: dist/index.handler
    events:
      - http:
          path: /{proxy+}
          method: any
